name: cicd_test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: pip install -r requirements.txt

      - name: deploy
        run: python app.py
      
